// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const databaseUrl = process.env.DATABASE_URL;
const directUrl = process.env.DIRECT_URL ?? process.env.DIRECT_DATABASE_URL ?? databaseUrl;
const fallbackUrl = 'postgresql://localhost:5432/postgres';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Use the real connection URL when present, but keep a harmless fallback so
    // Prisma CLI commands can load during Docker builds without runtime env vars.
    url: directUrl ?? databaseUrl ?? fallbackUrl,
  },
});