// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const databaseUrl = process.env.DATABASE_URL;
const directUrl = process.env.DIRECT_URL ?? process.env.DIRECT_DATABASE_URL ?? databaseUrl;

if (!databaseUrl && !directUrl) {
  throw new Error('Missing DATABASE_URL or DIRECT_URL environment variable for Prisma');
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Use DIRECT_URL when available for migrations, but fallback to DATABASE_URL
    // so build-time generation works in Docker/Render without a direct connection URL.
    url: directUrl ?? databaseUrl,
  },
});